import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Greet from './greet'
import React, {useState} from 'react';

const geistSans = localFont({
    src: "./fonts/GeistVF.woff", variable: "--font-geist-sans", weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff", variable: "--font-geist-mono", weight: "100 900",
});

const FileDropInput = () => {
    const [filePath, setFilePath] = useState('');

    // 处理文件拖动事件
    const handleFileDrop = (e) => {
        // e.preventDefault();
        // e.stopPropagation();
        console.log(JSON.stringify(e))
        if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
            // 获取文件的绝对路径 (在 Tauri 项目中可以通过 path 属性获得)
            const droppedFile = e.dataTransfer.files[0];
            setFilePath(droppedFile.path);  // 在 Tauri 中可以直接获取文件的绝对路径
            e.dataTransfer.clearData();
        }
    };


    return (<div
        onDrop={handleFileDrop}
        style={{
            border: '2px dashed #ccc', padding: '20px', borderRadius: '8px', width: '300px', textAlign: 'center',
        }}
    >
        <input
            type="file"
            value={filePath}
            readOnly
            placeholder="Drag and drop a file here"
            style={{
                width: '100%', padding: '10px', borderRadius: '4px', border: '1px solid #ccc',
            }}
        />
    </div>);
};
export default function Home() {
    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
            <main className={styles.main}>
                <Greet/>

                <ol>
                    <li>
                        Get started by editing <code>pages/index.js</code>.
                    </li>
                    <li>Save and see your changes instantly.</li>
                </ol>


            </main>
            <footer className={styles.footer}>
                <FileDropInput/>
            </footer>
        </div>
    </>);
}
