on:
  schedule:
  - cron: "50 23 * * 0-6"
  push:
    branches:
    - master
jobs:
  build_exe:
    name: 生成 exe 可执行文件
    runs-on: ubuntu-22.04
    steps:
    - name: tauri-build
      run: npm run tauri build
      working-directory: ./
    
